---
- name: Check Disk Space and Run Yarn Cache Clean if Less Than 50%
  hosts: your_windows_host
  gather_facts: no

  tasks:
    - name: Get Free Space on D drive
      win_shell: '[math]::Round((Get-PSDrive D).Free/1GB,2)'
      register: free_space

    - name: Get Used Space on D drive
      win_shell: '[math]::Round((Get-PSDrive D).Used/1GB,2)'
      register: used_space

    - name: Calculate Free Space Percentage
      set_fact:
        free_space_percent: "{{ ((free_space.stdout | float) / ((free_space.stdout | float) + (used_space.stdout | float))) * 100 | round(2) }}"

    - name: Debug Free Space Percentage
      debug:
        msg: "Free space on D drive: {{ free_space_percent }}%"

    - name: Check Free Space and Run Yarn Cache Clean
      when: free_space_percent | float < 50
      win_shell: yarn cache clean -cache-folder="D:\\yarn_cache\\0"

